dbt_olist:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: "{{ env_var('DBT_METHOD') }}"
      project: "{{ env_var('DBT_PROJECT') }}"
      dataset: "{{ env_var('DBT_DATASET') }}"
      location: "{{ env_var('DBT_LOCATION') }}"
      keyfile: "{{ env_var('DBT_KEYFILE_PATH') }}"
      threads: "{{ env_var('DBT_THREADS') | int }}"
      priority: "{{ env_var('DBT_PRIORITY') }}"
      job_execution_timeout_seconds: "{{ env_var('DBT_JOB_TIMEOUT') | int }}"
      job_retries: "{{ env_var('DBT_JOB_RETRIES') | int }}"
      use_storage_api: false
