dbt_olist:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: "{{ env_var('DBT_METHOD', '') | trim or 'service-account' }}"
      project: "{{ env_var('DBT_PROJECT') }}"
      dataset: "{{ env_var('DBT_DATASET') }}"
      location: "{{ env_var('DBT_LOCATION', '') | trim or 'US' }}"
      keyfile: "{{ env_var('DBT_KEYFILE_PATH', '') | trim or '/tmp/gcp-key.json' }}"
      threads: "{{ (env_var('DBT_THREADS', '') | trim or '4') | int }}"
      priority: "{{ env_var('DBT_PRIORITY', '') | trim or 'interactive' }}"
      job_execution_timeout_seconds: "{{ (env_var('DBT_JOB_TIMEOUT', '') | trim or '300') | int }}"
      job_retries: "{{ (env_var('DBT_JOB_RETRIES', '') | trim or '1') | int }}"
      use_storage_api: false
