jobs:
  dbt:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./dbt_olist  # O erro estava aqui: precisa de 2 espaços a mais que o 'run'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Authenticate to GCP
        # Aqui usamos o caminho absoluto para garantir que o dbt encontre o arquivo
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" > /tmp/gcp-key.json

      - name: Install dbt
        run: |
          pip install --upgrade pip
          pip install dbt-bigquery

      - name: Install dbt Dependencies
        run: dbt deps

      - name: dbt Debug (Check Connection)
        run: dbt debug

      - name: Run CI (Pull Request)
        if: github.event_name == 'pull_request'
        run: |
          dbt seed --target dev
          dbt run --target dev
          dbt test --target dev

      - name: Run CD (Push to Main)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          dbt seed --target prod
          dbt run --target prod
          dbt test --target prod
          dbt docs generate --target prod